services:
  dolce:
    container_name: dolce
    image: dangrie158/dolce:latest
    restart: unless-stopped
    environment:
      DOCKER_HOST: /var/run/docker.sock
      DISCORD_WEBHOOK: https://discord.com/api/webhooks/${DISCORD_WEBHOOK}
      DOLCE_SUPERVISION_MODE: ALL
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume2/docker/dolce/:/var/run/dolce/
      - /volume2/docker/dolce/lockfile:/var/run/dolce/lockfile
