# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
    environment:
      TZ: "${TZ}"
      FTLCONF_webserver_api_password: "${PASSWORD}"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - /volume2/docker/pihole/etc-pihole:/etc/pihole
    cap_add:
      # Optional for scheduling/background priority
      - SYS_NICE
